### ISSUE TITLE
Allow for overlaping directories in tenant definitions

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-spring-boot-deployment#11]
### Scenario

* Library version: 1.20.1
* Description of your use case: As a developer introducing the library, I want to be able to deploy processes from the root of the classpath to no tenant (not changing previous behaviour before the library introduction) and define locations beneath the root of the classpath for new tenants. 

### Current Behaviour

Not supported.

### Wanted Behaviour

Support the following use case:

```yaml

camunda:
  bpm:
    deployment:
      enabled: true
      archives:
        - name: Default
          path: overlapping
        - name: Bar
          tenant: bar
          path: overlapping/bar

```

As a result, process definitions from `overlapping/bar` are deployed in `Bar` tenant only, the process definitions from all other directories beneath `overlapping` should be deployed without tenant.  

### Possible Workarounds

None
